version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "7000:8080"
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - config:/mosquitto/config:rw
      - data:/mosquitto/data:rw
      - log:/mosquitto/log:rw
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  my-db:
  config:
  data:
  log:
