version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
  mongodb_actuator:
    image: mongo:latest
    container_name: "mongodb_actuator"
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - mongo-db-actuator:/data/db
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./config:/mosquitto/config:rw
      - data:/mosquitto/data:rw
      - log:/mosquitto/log:rw
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  my-db:
  mongo-db:
  config:
  data:
  log:
  mongo-db-actuator:
