spring:
  application:
    name: actuators
  data:
    mongodb:
      uri: mongodb://localhost:27020/actuator

server :
  port : 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Eureka server host
  instance:
    preferIpAddress: true # Optional, for preferring IP address in registration

