spring:
  application:
    name: stat

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Eureka server host
  instance:
    preferIpAddress: true # Optional, for preferring IP address in registration
