spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: sensors
          uri: lb://sensors # Load balance the request to the sensors service
          predicates:
            - Path=/api/** # Route the request to the sensors service if the path starts with /api
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
