spring:
  application:
    name: service-registry
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false # Don't register itself in the registry
    fetchRegistry: false # Don't fetch the registry, eurela is the main registry
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    renewal-percent-threshold: 0.85 # Renew the lease when 85% of the lease duration has passed
